// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gueboihmpxqygpisazdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZWJvaWhtcHhxeWdwaXNhemRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMTQ5NzAsImV4cCI6MjA1NDY5MDk3MH0.7hcZIITeU5LW-ruA71npGL4wt2Kx9BC6clSB72pdqW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);